### ISSUE TITLE
how fine-tune ems2 with DNA glycosylases?

### ISSUE THREAD

**Issue by contestq** [westlake-repl/ProteinLM-TDG2-Mutation#1]
question about fine-tune ems2 with DNA glycosylases? how to retrain esm2
thanks

**Comment by zhoubay** [comment]
We use the same config with esm2 to finetune the model with DNA glycosylases data, and the code is from another project.

For your convenience, you can refer to [this link](https://github.com/westlake-repl/SaProt/blob/main/README.md#fine-tune-saprot) to find training details :)

Thank you for leaving messages! Have a good day!

**Comment by contestq** [comment]
thanks for your reply! @zhoubay

**Comment by zhoubay** [comment]
> thanks for your reply! @zhoubay

You're welcome! Contact me if there's more issues! Gonna close this issue:)
