### ISSUE TITLE
What configuration is required to use this program and can it run without a GPU?

### ISSUE THREAD

**Issue by penglbio** [westlake-repl/ProteinLM-TDG2-Mutation#2]
I want to do same analysis for my own protein. I don't have computing resources. I want to know if I can run normally without GPU.
and the esm2 model files are inclued  tf_model.h5 and pytorch_model.bin. I show download which one?

**Comment by zhoubay** [comment]
sorry for late reply!

As far as we know, our model could be used when GPU is disabled.

And the `pytorch_model.bin` is needed since our model is implemented in pytorch framework.

**Comment by zhoubay** [comment]
If there's no more issues, I'll close this issue, feel free to reopen it!
