### ISSUE TITLE
Cann't got same output

### ISSUE THREAD

**Issue by penglbio** [westlake-repl/ProteinLM-TDG2-Mutation#3]
I repeated your procedure and found that the results were inconsistent with yours. Although the first mutation is consistent, the other rankings and fitness scores are different.

**Comment by zhoubay** [comment]
Please check the model and the code version.

The model and strategy combination in the results is (esm2_t48_15B_UR50D, esm1v_5).

And please check the latest code version in master branch.

**Comment by zhoubay** [comment]
If there's no more issues, I'll close this issue, feel free to reopen it!
